#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ruby-beautify
Version  : 0.92.2
Release  : 2
URL      : https://rubygems.org/downloads/ruby-beautify-0.92.2.gem
Source0  : https://rubygems.org/downloads/ruby-beautify-0.92.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-ruby-beautify-bin
BuildRequires : ruby
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support

%description
# RBeautify
This gem provides a cli binary named 'rbeautify' that will pretty up ruby code.

%package bin
Summary: bin components for the rubygem-ruby-beautify package.
Group: Binaries

%description bin
bin components for the rubygem-ruby-beautify package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ruby-beautify-0.92.2
gem spec %{SOURCE0} -l --ruby > rubygem-ruby-beautify.gemspec

%build
gem build rubygem-ruby-beautify.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ruby-beautify-0.92.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/ruby-beautify-0.92.2
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/ruby-beautify-0.92.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/Object/addLine-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/Object/beautifyRuby-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/Object/makeTab-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockEnd/after_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockEnd/block_start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockEnd/cdesc-BlockEnd.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockEnd/end_can_also_be_start%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockEnd/end_offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockEnd/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockEnd/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockEnd/offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/can_nest%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/cdesc-BlockMatcher.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/debug%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/debug-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/end_can_also_be_start%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/end_is_implicit%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/ends%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/ends-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/escape_character%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/evaluate_option_for_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/first_block_start-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/format_content%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/indent_end_line%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/indent_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/language-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/negate_ends_match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/parse-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/parse_block_start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/parse_content%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockMatcher/starts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/after_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/ancestors-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/block_matcher-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/cdesc-BlockStart.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/end_is_implicit%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/end_offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/ends%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/escape_character%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/first_common_ancestor-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/format_content%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/indent_end_line%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/indent_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/line_number-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/negate_ends_match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/offset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/parent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/parse_block_end-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/parse_content%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/parse_explicit_block_end-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/strict_ancestor_of%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/BlockStart/total_indent_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Language/add_language-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Language/add_matcher-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Language/cdesc-Language.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Language/indent_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Language/language-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Language/languages-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Language/matcher-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Language/matchers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Language/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/cdesc-Line.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/content-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/format%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/indent_character-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/indent_size-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/language-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/line_number-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/original_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/stripped-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/Line/tab_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/beautify_string-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/RBeautify/cdesc-RBeautify.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-beautify-0.92.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/README.md
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/RELEASE.md
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/bin/rbeautify
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/lib/beautifier.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/lib/ruby-beautify.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/lib/ruby-beautify/block_end.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/lib/ruby-beautify/block_matcher.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/lib/ruby-beautify/block_start.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/lib/ruby-beautify/config/ruby.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/lib/ruby-beautify/language.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/lib/ruby-beautify/line.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/lib/ruby-beautify/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/ruby-beautify.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/spec/fixtures/ruby.yml
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/spec/rbeautify/block_matcher_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/spec/rbeautify/block_start_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/spec/rbeautify/config/ruby_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/spec/rbeautify/line_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/spec/rbeautify_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-beautify-0.92.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/ruby-beautify-0.92.2.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/rbeautify
